### ISSUE TITLE
只抓到填报不够，请求帮助！

### ISSUE THREAD

**Issue by ikaroso** [iflynews/dxxcheckin#1]
你好兄弟，我是浙江的。
之前抓到了post请求，附上学号之类的data，就能被学校统计了。https://qczj.h5yunban.com/answer_apply_zj/webservice.php，这是抓到的post请求地址。
现在只提交post请求给他，已经无法被学校记录了，应该是需要看完视频才能被记录，但是从视频开始播放到结束，并没能抓到代表“看完了”的post请求。
兄弟有兴趣帮我一下的话可以去我们做大学习的公众号看看，“青春浙江”。
或者也可以给我留个QQ、微信，咱们看看能不能把他给安排了。

**Comment by iflynews** [comment]
我们学校最近期中考试，忙于复习，所以暂时没有多余的时间帮忙抓包，等过几天我考完期中考试了，我会帮忙看看的，抱歉了

**Comment by ZUHXS** [comment]
同浙江，加个微信讨论下？zuhxs-1

**Comment by ikaroso** [comment]
浙江的在统计时会使用微信id作为后台标识符，应该是没救了
